version: "3.8"

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
